import property1 from '../../assets/images/property1.svg';
import property2 from '../../assets/images/property2.svg';
import property3 from '../../assets/images/property3.svg';
import property4 from '../../assets/images/property4.svg';
import property5 from '../../assets/images/property5.svg';
import property6 from '../../assets/images/property6.svg';
import property7 from '../../assets/images/property7.svg';
import property8 from '../../assets/images/property8.svg';
import property9 from '../../assets/images/property9.svg';
import property10 from '../../assets/images/property10.svg';
import property11 from '../../assets/images/property11.svg';
import property12 from '../../assets/images/property12.svg';
import property13 from '../../assets/images/property13.svg';
import property14 from '../../assets/images/property14.svg';
import property15 from '../../assets/images/property15.svg';
import property16 from '../../assets/images/property16.svg';
import property17 from '../../assets/images/property17.svg';
import property18 from '../../assets/images/property18.svg';
import location from '../../assets/icon/location.svg';
import distane from '../../assets/icon/distance.svg';
import slot from '../../assets/icon/slot.svg';

export const LuxuryProducts = [{
    id: "1",
    Image: property1,
    location: location,
    title: "Modern design and high-end finishes",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$500 min. 8% ROI/p.a",
    slot: slot,
    slotnumber: "5 slots open",
    amount: "$450,000",
},
{
    id: "2",
    Image: property2,
    location: location,
    title: "Modern design and high-end finishes",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "10% ROI/p.a",
    slot: slot,
    slotnumber: "Outright purchase",
    amount: "$450,000",
},
{
    id: "3",
    Image: property3,
    location: location,
    title: "Modern design and high-end finishes",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$500 min. 8% ROI/p.a",
    slot: slot,
    slotnumber: "15 slots open",
    amount: "$450,000",
},
{
    id: "4",
    Image: property4,
    location: location,
    title: "Modern design and high-end finishes",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "8% ROI/p.a",
    slot: slot,
    slotnumber: "Outright purchase",
    amount: "$6,350,000",
},
{
    id: "5",
    Image: property5,
    location: location,
    title: "Modern design and high-end finishes",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$500 min. 8% ROI/p.a",
    slot: slot,
    slotnumber: "20 slots open",
    amount: "$450,000",
},
{
    id: "6",
    Image: property6,
    location: location,
    title: "Modern design and high-end finishes",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$500 min. 8% ROI/p.a",
    slot: slot,
    slotnumber: "15 slots open",
    amount: "$450,000",
}]

export const CommercialProduct = [{
    id: "1",
    Image: property7,
    location: location,
    title: "High-traffic area perfect for businesses",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$6500/pm/12 months",
    slot: slot,
    slotnumber: "2 years lease",
    amount: "$5,200,000",
},
{
    id: "2",
    Image: property8,
    location: location,
    title: "High-traffic area perfect for businesses",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$500 min. 8% ROI/p.a",
    slot: slot,
    slotnumber: "5 slot open",
    amount: "$3,500,000",
},
{
    id: "3",
    Image: property9,
    location: location,
    title: "High-traffic area perfect for businesses",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$500 min. 8% ROI/p.a",
    slot: slot,
    slotnumber: "Negotiable",
    amount: "$1,200,000",
},
{
    id: "4",
    Image: property10,
    location: location,
    title: "High-traffic area perfect for businesses",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$6500/pm/12 months",
    slot: slot,
    slotnumber: "2 years lease",
    amount: "$5,200,000",
},
{
    id: "5",
    Image: property11,
    location: location,
    title: "High-traffic area perfect for businesses",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$500 min. 8% ROI/p.a",
    slot: slot,
    slotnumber: "5 slots open",
    amount: "$3,500,000",
},
{
    id: "6",
    Image: property12,
    location: location,
    title: "High-traffic area perfect for businesses",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$500 min. 8% ROI/p.a",
    slot: slot,
    slotnumber: "Negotiable",
    amount: "$1,200,000",
}]

export const ResidentialProduct = [{
    id: "1",
    Image: property13,
    location: location,
    title: "Modern design and high-end finishes",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "8% ROI/p.a",
    slot: slot,
    slotnumber: "Outright purchase",
    amount: "$6,350,000",
},
{
    id: "2",
    Image: property14,
    location: location,
    title: "Modern design and high-end finishes",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$500 min. 8% ROI/p.a",
    slot: slot,
    slotnumber: "20 slots open",
    amount: "$450,000",
},
{
    id: "3",
    Image: property15,
    location: location,
    title: "Modern design and high-end finishes",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$500 min. 8% ROI/p.a",
    slot: slot,
    slotnumber: "15 slots open",
    amount: "$450,000",
},
{
    id: "4",
    Image: property16,
    location: location,
    title: "Modern design and high-end finishes",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "8% ROI/p.a",
    slot: slot,
    slotnumber: "Outright purchase",
    amount: "$6,350,000",
},
{
    id: "5",
    Image: property17,
    location: location,
    title: "Modern design and high-end finishes",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$500 min. 8% ROI/p.a",
    slot: slot,
    slotnumber: "20 slots open",
    amount: "$450,000",
},
{
    id: "6",
    Image: property18,
    location: location,
    title: "Modern design and high-end finishes",
    address: "Manhattan, USA",
    distane: distane,
    distancenumber: "$500 min. 8% ROI/p.a",
    slot: slot,
    slotnumber: "15 slots open",
    amount: "$450,000",
}]